project-includes = ["backend/app"]
project-excludes = ["**/__pycache__", "**/*venv/**", "**/.git/**", "**/node_modules/**"]
search-path = ["backend"]
python-interpreter-path = "backend/.venv/bin/python"
